files:
  "/etc/nginx/conf.d/proxy.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      server {
        server_name localhost;
        types_hash_max_size 2048;
        types_hash_bucket_size 128;
      }